### ISSUE TITLE
How to add more than 1 admins, or mods in the setup config

### ISSUE THREAD

**Issue by apatel190** [Pedro-Pessoa/Reaction-Ticket-CC#3]
Tittle says all what do I change, I know it says remove "cslice" but how do I separate the ids?

**Comment by Pedro-Pessoa** [comment]
Title does not say to remove the cslice.
Title says to keep the cslice there, even if you have only 1 role.
The way to do it is just put whatever roles you want
`{{$Mods := cslice 674429313097007106 673258482211749917 647298324734541827}}`

**Comment by apatel190** [comment]
> Title does not say to remove the cslice.
> Title says to keep the cslice there, even if you have only 1 role.
> The way to do it is just put whatever roles you want
> `{{$Mods := cslice 674429313097007106 673258482211749917 647298324734541827}}`

ty for the quick reply, didn't read it properly 😅
